<?php

namespace Database\Seeders;

use App\Models\desa;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DesaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            'Ajung',
            'Klompangan',
            'Mangaran',
            'Pancakarya',
            'Rowoindah',
            'Sukamakmur',
            'Wirowongso',
            'Ambulu',
            'Andongsari',
            'Karang Anyar',
            'Pontang',
            'Sabran',
            'Sumberejo',
            'Tegalsari',
            'Arjasa',
            'Biting',
            'Candijati',
            'Darson',
            'Kamal',
            'Kemuning Lor',
            'Badean',
            'Bangsalsari',
            'Banjarsari',
            'Curahkalong',
            'Gambirono',
            'Karangsono',
            'Langkap',
            'Petung',
            'Sukorejo',
            'Tisnogambar',
            'Tugusari',
            'Balung Kidul',
            'Balung Kulon',
            'Balung Lor',
            'Curahlele',
            'Gumelar',
            'Karangduren',
            'Karang Semandin',
            'Tutul',
            'Bagorejo',
            'Gumukmas',
            'Karangrejo',
            'Kepanjen',
            'Mayangan',
            'Menampu',
            'Purwoasri',
            'Tembokrejo',
            'Jelbuk',
            'Panduman',
            'Sucopangepok',
            'Sugerkidul',
            'Sukojember',
            'Sukowiryo',
            'Cangkring',
            'Jatimulyo',
            'Jatisari',
            'Jenggawah',
            'Kemuningsari Kid',
            'Kertonegoro',
            'Sruni',
            'Wonojati',
            'Jombang',
            'Keting',
            'Ngampelrejo',
            'Padomasan',
            'Sarimulyo',
            'Wringinagung',
            'Ajung',
            'Gambiran',
            'Glagahwero',
            'Gumuksari',
            'Kalisat',
            'Patempuran',
            'Plalangan',
            'Sebanen',
            'Sukoreno',
            'Sumberjeruk',
            'Sumberkalong',
            'Sumberketempa',
            'Mangli',
            'Jember Kidul',
            'Kaliwates',
            'Kebon Agung',
            'Kepatihan',
            'Sempusari',
            'Tegal Besar',
            'Cakru',
            'Kencong',
            'Kraton',
            'Paseban',
            'Wonorejo',
            'Karangpaiton',
            'Ledokombo',
            'Lembengan',
            'Slateng',
            'Sukogidri',
            'Sumberanget',
            'Sumberbulus',
            'Sumberlesung',
            'Sumbersalak',
            'Suren',
            'Mayang',
            'Mrawan',
            'Seputih',
            'Sidomukti',
            'Sumberkejayan',
            'Tegalrejo',
            'Tegalwaru',
            'Karang Kedawung',
            'Kawangrejo',
            'Lampeji',
            'Lengkong',
            'Mumbulsari',
            'Suco',
            'Tamansari',
            'Glagahwero',
            'Kemiri',
            'Kemuningsari Lor',
            'Pakis',
            'Panti',
            'Serut',
            'Suci',
            'Bedadung',
            'Jatian',
            'Kertosari',
            'Pakusari',
            'Patemon',
            'Subo',
            'Sumberpinang',
            'Patrang',
            'Banjarsengon',
            'Baratan',
            'Bintoro',
            'Gebang',
            'Jemberlor',
            'Jumerto',
            'Slawu',
            'Bagon',
            'Grenden',
            'Jambearum',
            'Kasiyan',
            'Kasiyan Timur',
            'Mlokorejo',
            'Mojomulyo',
            'Mojosari',
            'Puger Kulon',
            'Puger Wetan',
            'Wonosari',
            'Wringintelu',
            'Curahmalang',
            'Gugut',
            'Kaliwining',
            'Nogosari',
            'Pecoro',
            'Rambigundam',
            'Rambipuji',
            'Rowotamtu',
            'Pondokdalem',
            'Pondokjoyo',
            'Rejoagung',
            'Semboro',
            'Sidomekar',
            'Sidomulyo',
            'Garahan',
            'Harjomulyo',
            'Karangharjo',
            'Mulyorejo',
            'Pace',
            'Sempolan',
            'Sidomulyo',
            'Silo',
            'Sumberjati',
            'Dukuhmencek',
            'Jubung',
            'Karangpring',
            'Klungkung',
            'Sukorambi',
            'Arjasa',
            'Balet Bar',
            'Dawuhanmangli',
            'Mojogemi',
            'Pocangan',
            'Sukokerto',
            'Sukorejo',
            'Sukosari',
            'Sukowono',
            'Sumberwringin',
            'Sumberdanti',
            'Sumberwaru',
            'Gelang',
            'Jambesari',
            'Jamintoro',
            'Jatiroto',
            'Kaliglagah',
            'Karangbayat',
            'Pringgowirawan',
            'Rowotengah',
            'Sumberagung',
            'Yosorati',
            'Cumedak',
            'Gunungmalang',
            'Jambearum',
            'Plerean',
            'Pringgondani',
            'Randuagung',
            'Rowosari',
            'Sumberjambe',
            'Sumberpakem',
            'Antirogo',
            'Karangrejo',
            'Kebonsari',
            'Kranjingan',
            'Sumbersari',
            'Tegalgede',
            'Wirolegi',
            'Darungan',
            'Klatakan',
            'Kramat',
            'Sukoharjo',
            'Manggisan',
            'Patemon',
            'Selodakon',
            'Tanggul Kulon',
            'Tanggul Wetan',
            'Andongrejo',
            'Curahnongko',
            'Curahtakir',
            'Pondokrejo',
            'Sidodadi',
            'Sanenrejo',
            'Tempurejo',
            'Wonoasri',
            'Gadingrejo',
            'Gunungsari',
            'Mundurejo',
            'Paleran',
            'Sidorejo',
            'Sukoreno',
            'Tanjungsari',
            'Tegalwangi',
            'Umbulrejo',
            'Umbulsari',
            'Ampel',
            'Dukuhdempok',
            'Glundengan',
            'Kesilir',
            'Lojejer',
            'Tamansari',
            'Tanjungrejo',
        ];

        // Buat entri untuk setiap desa
        foreach ($data as $desa) {
            desa::create([
                'desa' => $desa,
            ]);
        }
    }
}
